### ISSUE TITLE
StrictMode DiskReadViolation crash in SharedPreferences

### ISSUE THREAD

**Issue by maksym-moroz** [Netvent/storyly-sdk#362]
Issue tracker is **ONLY** used for reporting Android SDK related bugs.

## Environment Details
**Storyly SDK Version:** 2.17.1
**Android SDK Version:** 34
**Device Model:** Pixel 3a Emulator
**Device OS Version:** Android 14
**Additional Info:** Emulator running on M1 Mac chip

## Expected Behavior

No crash nor any StrictMode violations
## Current Behavior

StrictMode DiskReadViolation crashes the app
## Steps to Reproduce

1. Init Storyly SDK

`FATAL EXCEPTION: pool-14-thread-1
                                                                                                    Process: ***.***.***.***, PID: 22698
                                                                                                    android.os.strictmode.DiskReadViolation
                                                                                                    	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1666)
                                                                                                    	at libcore.io.BlockGuardOs.access(BlockGuardOs.java:74)
                                                                                                    	at libcore.io.ForwardingOs.access(ForwardingOs.java:128)
                                                                                                    	at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:8054)
                                                                                                    	at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:313)
                                                                                                    	at java.io.File.exists(File.java:813)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:790)
                                                                                                    	at android.app.ContextImpl.ensurePrivateDirExists(ContextImpl.java:781)
                                                                                                    	at android.app.ContextImpl.getPreferencesDir(ContextImpl.java:737)
                                                                                                    	at android.app.ContextImpl.getSharedPreferencesPath(ContextImpl.java:962)
                                                                                                    	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:583)
                                                                                                    	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:221)
                                                                                                    	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:221)
                                                                                                    	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:221)
                                                                                                    	at com.appsamurai.storyly.data.managers.network.d.a(RequestParameterGenerator.kt:279)
                                                                                                    	at com.appsamurai.storyly.analytics.e.a(StorylyTracker.kt:794)
                                                                                                    	at com.appsamurai.storyly.analytics.e.a(StorylyTracker.kt:180)
                                                                                                    	at com.appsamurai.storyly.analytics.d.a(StoryGroupImpressionManager.kt:48)
                                                                                                    	at com.appsamurai.storyly.storylylist.StorylyListRecyclerView$2.onLayoutCompleted(StorylyListRecyclerView.kt:3)`

**Comment by yigcal** [comment]
Hello @maksym-moroz,

We have tested our SDK by enabling StrictMode in our demo project with latest SDK versions. Please update to the latest version and observe the issue.

Thanks
