### ISSUE TITLE
Shoppable stories crash after missing internet connection

### ISSUE THREAD

**Issue by wrozwad** [Netvent/storyly-sdk#392]
With randomly disappearing internet bottom sheets with product details from Shoppable Stories can crash the app.

## Environment Details
**Storyly SDK Version:** `3.6.0`, `4.3.0`
**Android SDK Version:** api `33`, `35`
**Device Model:** Galaxy S20 FE 5G, Emulator
**Device OS Version:** Android `13`, `15`
**Additional Info:** ---

## Expected Behavior

Product photos should appear after internet connection is restored, alternatively just avoiding the crash would be enough.

## Current Behavior

App crashes with this stacktrace:
```
FATAL EXCEPTION: main (Ask Gemini)
Process: pl.superpharm.stage, PID: 32702
com.bumptech.glide.load.engine.CallbackException: Unexpected exception thrown by non-Glide code
        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:160)
        at com.bumptech.glide.load.engine.EngineJob$CallResourceReady.run(EngineJob.java:424)
        at android.os.Handler.handleCallback(Handler.java:959)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loopOnce(Looper.java:232)
        at android.os.Looper.loop(Looper.java:317)
        at android.app.ActivityThread.main(ActivityThread.java:8705)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
Caused by: java.lang.IllegalStateException: The specified child already has a parent. You must call removeView() on the child's parent first.
        at android.view.ViewGroup.addViewInner(ViewGroup.java:5256)
        at android.view.ViewGroup.addView(ViewGroup.java:5085)
        at android.view.ViewGroup.addView(ViewGroup.java:5057)
        at com.appsamurai.storyly.storylypresenter.product.imagelist.f$d.invoke(StorylyProductImageView.kt:12)
        at com.appsamurai.storyly.storylypresenter.product.imagelist.g.onResourceReady(StorylyProductImageView.kt:8)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:622)
        at com.bumptech.glide.request.SingleRequest.onResourceReady(SingleRequest.java:575)
        at com.bumptech.glide.load.engine.EngineJob.callCallbackOnResourceReady(EngineJob.java:158)
        ... 9 more
```

## Steps to Reproduce

https://github.com/user-attachments/assets/400ca935-dfc4-474d-ae56-4f4c02201bd7

1. Launch a previously unvisited story with internet connection enabled. Make sure the given product has some photos
2. Before clicking the "Buy now" CTA, turn off the internet
3. Click the "Buy now" CTA - a bottom sheet will appear
4. Turn on internet and return to the application

**Comment by levent-oral** [comment]
Hello @wrozwad ,

we've fixed this issue in [storyly-android-sdk@4.4.0](https://github.com/Netvent/storyly-sdk/blob/master/android/RELEASENOTES.md#440-28112024) and [storyly-android-sdk@3.9.0](https://github.com/Netvent/storyly-sdk/blob/master/android/RELEASENOTES.md#390-28112024) versions.

Thanks,
