### ISSUE TITLE
ExoPlayer$Builder.<init> java.lang.NoClassDefFoundError - f12 

### ISSUE THREAD

**Issue by vaibhav-reddoorz** [Netvent/storyly-sdk#397]
Issue tracker is **ONLY** used for reporting Android SDK related bugs.

## Environment Details
**Storyly SDK Version:** 4.3.0

**Android OS Version:** 

> Android 5 (97%)
> 87% Android 5.1
> 10% Android 5.1.1

> Android 6 (3%)
> 3% Android 6.0.1

**Device Model:** 

> Oppo (93%)
> 83% Oppo F1s 
> 7% A37f 
> 3% CPH1605

> Samsung (7%)
> 4% Galaxy J3(2016)
> 3% Galaxy J2 Prime

Crash line number:

> com.appsamurai.storyly.exoplayer2.core
> ExoPlayer.java:516

Getting issue at Android 5 and Android 6 version. 

          Fatal Exception: java.lang.NoClassDefFoundError: y22
       at com.appsamurai.storyly.exoplayer2.core.ExoPlayer$Builder.<init>(ExoPlayer.java:516)
       at com.appsamurai.storyly.storylylist.q.f(q.java:1)
       at com.appsamurai.storyly.storylylist.StorylyListRecyclerView$h.invoke(StorylyListRecyclerView.kt:12)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at com.appsamurai.storyly.storylylist.StorylyListRecyclerView.getStoryGroupVideoPlayer(StorylyListRecyclerView.kt)
       at com.appsamurai.storyly.storylylist.StorylyListRecyclerView.d(StorylyListRecyclerView.kt)
       at com.appsamurai.storyly.StorylyView.onWindowFocusChanged(StorylyView.kt:8)
       at android.view.View.dispatchWindowFocusChanged(View.java:8848)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1086)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1090)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1090)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1090)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1090)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1090)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1090)
       at android.view.ViewGroup.dispatchWindowFocusChanged(ViewGroup.java:1090)
       at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3819)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:224)
       at android.app.ActivityThread.main(ActivityThread.java:5911)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

<img width="1124" alt="Screenshot 2024-11-22 at 11 40 41 AM" src="https://github.com/user-attachments/assets/e004c36c-ec46-4a02-8aac-8ecafc9036ce">

**Comment by vaibhav-reddoorz** [comment]
Hi @levent-oral ,

Thank you for your response and the detailed insights into the issue.

While we appreciate your suggestion to disable support for Android 5 and 6 and start Storyly integration from Android 7, we believe this is not an ideal solution. The decision to drop support for these versions impacts users who are still on older Android devices, even if their distribution is low.

Additionally, the StackOverflow link you shared does not seem directly relevant to resolving this issue. We strongly recommend addressing the ExoPlayer integration within your SDK to ensure compatibility with Android 5 and 6. It's important to provide a robust SDK that aligns with its stated minimum support version.

We also noticed that your sample code specifies a minimum version of 21 (Android 5). If this is the case, the SDK should be capable of supporting this minimum version without crashes. Disabling support for Android 5 and 6 should be a last resort only after exhausting all potential fixes within the SDK.

While disabling support below Android 7 prevents crashes on our side, this workaround is not an optimal long-term solution. We hope you can address this issue promptly, as it also affects our user experience.

Looking forward to your feedback and a fix for this matter.

Regards,
Vaibhav
